Vagrant.configure("2") do |config|
  # Provision común
  config.vm.provision "shell", inline: "echo Hello"

  # VM web01
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.network "private_network", ip: "192.168.23.65"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus   = 3
    end

    web01.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install apache2 wget unzip -y
      systemctl start apache2
      systemctl enable apache2
      cd /tmp/
      wget https://www.tooplate.com/zip-templates/2131_wedding_lite.zip
      unzip -o 2131_wedding_lite.zip
      cp -r 2131_wedding_lite/* /var/www/html/
      systemctl restart apache2
    SHELL
  end  # cierra web01

  # VM db01
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/7"
    db01.vm.network "private_network", ip: "192.168.23.65"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus   = 3
    end

    db01.vm.provision "shell", inline: <<-SHELL
      yum install -y mariadb-server
      systemctl start mariadb
      systemctl enable mariadb

      mysql -u root -e "CREATE DATABASE wordpress;"
      mysql -u root -e "CREATE USER 'wordpressuser'@'localhost' IDENTIFIED BY 'admin123';"
      mysql -u root -e "GRANT SELECT, INSERT, UPDATE, DELETE ON wordpress.* TO 'wordpressuser'@'localhost';"
      mysql -u root -e "FLUSH PRIVILEGES;"
    SHELL
  end  # cierra db01

end  # cierra Vagrant.configure
